apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apnacart-app
  namespace: argocd
spec:
  project: default
  source:
    # Replace this with your actual GitHub repository URL
    repoURL: 'https://github.com/SirLance007/apnacart-gitops.git'
    targetRevision: HEAD
    path: kubernetes/apnacart-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
