apiVersion: v1
kind: ServiceAccount
metadata:
  name: apnacart-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apnacart-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apnacart
  template:
    metadata:
      labels:
        app: apnacart
      annotations:
        # 1. Enable Vault agent injection
        vault.hashicorp.com/agent-inject: "true"
        # 2. Specify the Vault role we bound to this ServiceAccount
        vault.hashicorp.com/role: "apnacart-role"
        # 3. Specify the secret path to fetch from Vault
        vault.hashicorp.com/agent-inject-secret-db-creds: "secret/data/apnacart/db-creds"
        # 4. Format the injected secret as standard key=value pairs
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "secret/data/apnacart/db-creds" -}}
          DB_USER="{{ .Data.data.username }}"
          DB_PASS="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: apnacart-sa
      containers:
      - name: apnacart
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "=== 🚀 Starting ApnaCart Store App ==="
          while true; do
            if [ -f /vault/secrets/db-creds ]; then
              echo "--- 🔑 Injected secrets from Vault locker: ---"
              cat /vault/secrets/db-creds
            else
              echo "⚠️ Waiting for Vault to inject secrets..."
            fi
            sleep 15
          done
